#ifndef COSMO_MESSAGE_STATUS_H
#define COSMO_MESSAGE_STATUS_H

enum cosmoMessageStatus
{
    COSMO_MESSAGE_STATUS_OK,
    COSMO_MESSAGE_STATUS_ERROR,
    COSMO_MESSAGE_MALLOC_FAILED
};

#endif // COSMO_MESSAGE_STATUS_H