name: Continous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  COMPILER_X86: gcc
  BUILD_DIR: ./build/default

jobs:
  tests:
    runs-on: ubuntu-latest
    container: 
      image: docker.io/joseamador95/devcontainer:main
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Config
      run: cmake --preset default -G Ninja --fresh

    - name: Build Lib
      run: cmake --build --preset default

    - name: Unit Tests
      run: ctest --preset default
    
    - name: Code Coverage
      run: cmake --build --preset default --target gcovr_html

    - name: Code Formatting
      run: cmake --build --preset default --target clangformat_check

    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: ${{env.BUILD_DIR}}
